### PR TITLE
Fix local tests

### PR DESCRIPTION
**Pull request by Victoremepunto**
Follow up of #15

### CODE REVIEW

**Comment by skateman** [comment]
Maybe we should consider running the tests from the container locally if the setup is so complicated. Like start up in the compose file a sleeping container and just docker exec?

**Comment by Victoremepunto** [comment]
> Maybe we should consider running the tests from the container locally if the setup is so complicated. Like start up in the compose file a sleeping container and just docker exec?

Well - this was in case you wanted to run tests locally - like - running the `pytest` command on your local machine , against configured pods (the DB and the MinIO bucket) that come up with the compose template.

The tests we run on CI actually run within a container, using the `docker exec` approach you mention. 

So what I mean is, we are just fixing the local tests here (for running pytest locally), which helps with development. The entire issue was just essentially a misconfigured DB pod (the environment variables of it). 

So ... if you're cool with it I think we can merge this fix ? otherwise - the docker-compose template and all is ... a bit of useless. I do think it provides some value to be able to run it locally but it's your call :) 

also, FYI I also created #18  to track the Python 3.10 compat.

**Review by skateman — APPROVED** [review]
The Seal of Approval

**Pull request merged**
